### ISSUE TITLE
Add trained models

### ISSUE THREAD

**Issue by bojobo** [SamSweere/xmm-superres-denoise#17]
For every trained model, add the checkpoint which performs the best.
Right now, there are .onnx files with the best-performing models, but using the PyTorch native .ckpt makes the inference as well as model inspection (if needed) easier. Also, convert the .ckpt to .onnx so that we have both.

I'll keep editing this list to track the status.

- [ ] ESR-GEN (baseline)
- [ ] SwinIR

**Comment by bojobo** [comment]
@SamSweere I tried to upload the checkpoints created up until now. Unfortunately, they take up about 350 MB (SwinIR has large checkpoint files), which is more than the allowed 0.5 MB. Should we increase the allowed file size, or should I look for another possibility to share the files?

**Comment by SamSweere** [comment]
The 0.5 MB limit can be ignored by using `git commit -m "" --no-verify`. However, adding big files to git is almost never desirable. We could maybe look to host it on huggingface? And pull the model if it is not present locally.

**Comment by bojobo** [comment]
Good point. I'll have a look into it. I'll leave the issue open just for tracking.
