### ISSUE TITLE
Use `dependabot` to keep dependencies up-to-date?

### ISSUE THREAD

**Issue by bojobo** [SamSweere/xmm-superres-denoise#20]
See [quick start guide](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide)
Maybe interesting to keep everything up-to-date?

**Comment by SamSweere** [comment]
Reaction might be a bit late. 
What problems would adding dependabot solve that we currently face? Since we do not have any tests I am not very inclined to automatically update dependencies.

**Comment by bojobo** [comment]
None, to be honest. It was just an idea I had at that time and forgot about it.
