### ISSUE TITLE
Request xmm_superres_denoise/run_config.yaml

### ISSUE THREAD

**Issue by jiaweimmiao** [SamSweere/xmm-superres-denoise#23]
I am sorry that I did not find this file in the directory xmm_superres_denoise/run_config.yaml
, can you provide it.

**Comment by bojobo** [comment]
Hi. You need to create one yourself based on the [template](https://github.com/SamSweere/xmm-superres-denoise/blob/master/res/run_config_template.yaml) that I've provided. The settings are explained in the file itself. If you have any further questions let me know.

**Comment by bojobo** [comment]
The baseline settings can be found [here](https://github.com/SamSweere/xmm-superres-denoise/blob/master/res/baseline_config.yaml). There you have to only add your own wandb parameters.

**Comment by jiaweimmiao** [comment]
Ok，thanks, I try it.
