### ISSUE TITLE
About how to generate those model input data?

### ISSUE THREAD

**Issue by leungzzz** [SamSweere/xmm-superres-denoise#24]
I had downloaded those data from [hugging face](https://huggingface.co/datasets/bojanto/xmm-superres-denoise/tree/main/sim_dataset). then next, how can i use these current ".fit" format datas to generate the train/test/val data?

**Comment by bojobo** [comment]
Hi!

I'm currently really busy with another part of my thesis. As soon as I have that running I'll get back to you.

**Comment by leungzzz** [comment]
> Hi!
> 
> I'm currently really busy with another part of my thesis. As soon as I have that running I'll get back to you.

thanks a lot! By the way, a little update have done in README.md file ( Inference part )?, the mentioned `inference_example.ipynb` & `xmm_superres_denoise/inference.py`, **could not to find** in this project ...

**Comment by leungzzz** [comment]
> > Hi!
> > I'm currently really busy with another part of my thesis. As soon as I have that running I'll get back to you.
> 
> thanks a lot! By the way, a little update have done in README.md file ( Inference part )?, the mentioned `inference_example.ipynb` & `xmm_superres_denoise/inference.py`, **could not to find** in this project ...



> > Hi!
> > I'm currently really busy with another part of my thesis. As soon as I have that running I'll get back to you.
> 
> thanks a lot! By the way, a little update have done in README.md file ( Inference part )?, the mentioned `inference_example.ipynb` & `xmm_superres_denoise/inference.py`, **could not to find** in this project ...

I was careless, got the answer in branch `xmmsr_ivan` .
